//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoatJira.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoatJira.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1250&quot;?&gt;
        ///&lt;MDG.Technology version=&quot;1.0&quot;&gt;&lt;Documentation id=&quot;Goat Jira&quot; name=&quot;Goat Jira - Be Connected with Jira&quot; version=&quot;1.0 Alfa&quot; notes=&quot;Will be added later on.&quot; infoURI=&quot;http://www.rydval.cz&quot; supportURI=&quot;slavek@rydval.cz&quot;/&gt;&lt;UMLProfiles&gt;&lt;UMLProfile profiletype=&quot;uml2&quot;&gt;
        ///			&lt;Documentation id=&quot;AAD8178D-1&quot; name=&quot;Goat Jira&quot; version=&quot;1.0&quot; notes=&quot;Goat Jira&quot;/&gt;
        ///			&lt;Content&gt;
        ///				&lt;Stereotypes&gt;
        ///					&lt;Stereotype name=&quot;JiraBug&quot; metatype=&quot;JiraBug&quot; notes=&quot;&quot; cx=&quot;0&quot; cy=&quot;0&quot; bgcolor=&quot;-1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GoatJiraMDG {
            get {
                return ResourceManager.GetString("GoatJiraMDG", resourceCulture);
            }
        }
    }
}
